name: Node builds

on:
  workflow_dispatch:

jobs:
  build-20-without-icu:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Determine latest Node v20 release
        id: release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          result-encoding: string
          script: |
            const req = await fetch('https://nodejs.org/download/release/index.json')
            const releases = await req.json()

            const latest = releases.find((r) => r.version.startsWith('v20'))
            return latest.version
      - name: Download and extract source
        run: curl https://nodejs.org/download/release/${{ steps.release.outputs.result }}/node-${{ steps.release.outputs.result }}.tar.xz | tar xfJ -
      - name: Install ninja
        run: sudo apt-get install ninja-build
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.12
      - name: Build
        working-directory: ./node-${{ steps.release.outputs.result }}
        run: |
          export CC="ccache gcc"
          export CXX="ccache g++"
          ./configure --without-intl --ninja --prefix=../node20-iculess
          make
          make install
      - uses: actions/upload-artifact@v4
        with:
          name: node20-iculess
          path: node20-iculess/
